services:
  backend:
    build: .
    container_name: hydrodrags-backend
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:8002:8000"
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.18
    container_name: hydrodrags-mongodb   # ðŸ‘ˆ ADD THIS
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: